// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1_search.Models.EfModels;

public partial class Category
{
    public int Id { get; set; }

    public string CategoryName { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}